### ISSUE TITLE
파이어폭스에서 한글 IME 밀림 문제

### ISSUE THREAD

**Issue by firefanda** [wormwlrm/military-service-calculator#10]
Element UI의 버그로 한글 IME에서 밀림 문제가 발생합니다.
Element UI v2.12.0에서 수정 예정이네요.

관련 PR: ElemeFE/element#15069 
관련 게시글: https://lovemewithoutall.github.io/it/element-ui-with-ie/

**Comment by wormwlrm** [comment]
앗, 이런 이슈가 있었군요.
5일 전에 머지가 된 걸로 봐서 다음 버전 안에 배포될 것 같으니, 
Element UI 새 버전이 배포되면 패키지 버전을 업그레이드 하겠습니다!
감사합니다. 🙏

**Comment by wormwlrm** [comment]
안녕하세요,
해당 문제의 원인을 v1.2.6 버전에서 업데이트하여 현재 릴리즈 중입니다. (https://github.com/wormwlrm/military-service-calculator/commit/ae8b755d601138df24f733cf6fd0070d6f3cbf68)
배포된 앱이 v1.2.6 버전으로 업데이트 되면 아마 문제가 없을 것으로 예상됩니다.
