### ISSUE TITLE
배포된 버전에서 개발 도구가 실행되고 있음

### ISSUE THREAD

**Issue by Jungwoo-An** [wormwlrm/military-service-calculator#11]
## 문제

- 배포된 버전에서 [webpack-chrome-extension-reloader](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader) 가 실행되고 있는 것 같습니다. 아무 프로젝트에서 위 라이브러리를 사용해서 개발 서버를 열면, 아래와 같이 연결되었다는 메시지가 출력됩니다.

![image](https://user-images.githubusercontent.com/17793088/71639343-34d1f100-2cb8-11ea-8bdc-2a180fac0521.png)

## 흥미진진

- [webpack-config](https://github.com/wormwlrm/military-service-calculator/blob/master/webpack.config.js#L108) 를 보면 HMR 환경 변수가 설정된 게 아니라면 포함되지 않을텐데, 호옥시 빌드 과정에서 해당 환경 변수가 잘못 설정된 건 아닐지... 👀

**Comment by wormwlrm** [comment]
안녕하세요 @Jungwoo-An 님, 이슈를 남겨주셔서 감사합니다.

이 문제 원인을 확인해보니 `process.env.HMR` 라는 옵션은 사용한 제가 [보일러플레이트의 기본 옵션](https://github.com/Kocal/vue-web-extension/blob/3b6d089ee6b163715fb1dfa99473814cc15d6ca0/examples/full-airbnb/package.json#L18) 중 하나인데, `package.json`을 보시면 `HMT`은 개발 서버를 켤 때만 초기화를 시켜주는 거라서 실제 빌드 시에는 초기화가 안되어 있어야 하는게 정상인게 맞는 것 같아요.

그래서 이 문제를 해결하기 위해 [프로덕션 환경에서 개발 서버의 웹 소켓을 리스닝 하고 있는 이슈](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/issues/43)를 확인했습니다. 하지만 이미 프로젝트 자체가 deprecated 된 상태여서, `vue-web-extension`에서 이를 어떻게 처리했는지를 확인해보니 보일러 플레이트 자체에서 [디펜던시 업데이트](https://github.com/Kocal/vue-web-extension/commit/cd68341014a7702a64e083b39996e5c471cad625)를 6월에 한 상태였습니다.

보일러 플레이트 자체를 업데이트 하기는 어려워서 위의 커밋대로 웹팩 리로더를 손으로 업데이트 할 예정입니다. 다만 이것으로 문제가 해결된다는 것을 보장하기에는 어렵지만, 한 번 시도해보고 알려드리겠습니다.

**Comment by Jungwoo-An** [comment]
@wormwlrm 빠른 피드백 감사합니다. 👍

1.2.7 버전으로 업데이트 해서 확인해봤고, 이상 없이 작동하는 것 같습니다. 감사합니다!
